name: easy_splash
description: "EasySplash is a lightweight Flutter package designed to streamline the implementation of splash screens in your Flutter applications."
version: 0.0.6
homepage: https://github.com/vigneshravi7117/easy_splash.git

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0